const CANNOT_START = 'CANNOT_START';
const CANNOT_STOP = 'CANNOT_STOP';
const PID_FILE_ERROR = 'PID_FILE_ERROR';
const LOG_FILE_ERROR = 'LOG_FILE_ERROR';
const PORT_IN_USE_ERROR = 'PORT_IN_USE_ERROR';
const BUSY_ERROR = 'BUSY_ERROR';
const START_PROCESS_ERROR = 'START_PROCESS_ERROR';
const NOT_READY_ERROR = 'NOT_READY_ERROR';
const BASH_SCRIPT_GEN_ERROR = 'BASH_SCRIPT_GEN_ERROR';
const BASH_SCRIPT_EXEC_ERROR = 'BASH_SCRIPT_EXEC_ERROR';
const TIMEOUT_ERROR = 'TIMEOUT_ERROR';
const OPERATION_NOT_PERMITTED_ERROR = 'OPERATION_NOT_PERMITTED_ERROR';
const ALREADY_STARTING = 'ALREADY_STARTING';
const ALREADY_STOPPING = 'ALREADY_STOPPING';
const CANCELLED = 'CANCELLED';

const GANACHE_ERROR = 'GANACHE_ERROR';
const DOCKER_ERROR = 'DOCKER_ERROR';
const FS_ERROR = 'FS_ERROR';
const DBDIR_ERROR = 'DBDIR_ERROR';
const POCO_ERROR = 'POCO_ERROR';
const IPFS_ERROR = 'IPFS_ERROR';
const REDIS_ERROR = 'REDIS_ERROR';
const GRADLEW_ERROR = 'GRADLEW_ERROR';
const MONGO_ERROR = 'MONGO_ERROR';
const CORE_ERROR = 'CORE_ERROR';
const WORKER_ERROR = 'WORKER_ERROR';
const MARKET_ERROR = 'MARKET_ERROR';
const PKGMGR_ERROR = 'PKGMGR_ERROR';
const GIT_ERROR = 'GIT_ERROR';
const SMS_ERROR = 'SMS_ERROR';
const SIGNATURE_CONFLICT_ERROR = 'SIGNATURE_CONFLICT_ERROR';
const MARKET_API_ERROR = 'MARKET_API_ERROR';
const MARKET_WATCHER_ERROR = 'MARKET_WATCHER_ERROR';
const DIRECTORY_DOES_NOT_EXIST = 'DIRECTORY_DOES_NOT_EXIST';
const DIRECTORY_ALREADY_EXISTS = 'DIRECTORY_ALREADY_EXISTS';
const FILE_DOES_NOT_EXIST = 'FILE_DOES_NOT_EXIST';
const FILE_ALREADY_EXIST = 'FILE_ALREADY_EXIST';
const YML_PARSE_ERROR = 'YML_PARSE_ERROR';

const NOT_STRICT_POSITVE_INT = 'NOT_STRICT_POSITVE_INT';
const NULLISH_OR_EMPTY_STRING = 'NULLISH_OR_EMPTY_STRING';

const ABORT = 'ABORT';
const TIMEOUT = 'TIMEOUT';
const PROCESS_KILLED = 'PROCESS_KILLED';
const NOT_READY = 'NOT_READY';
const UNKNOWN = 'UNKNOWN';

export {
    CANNOT_START,
    CANNOT_STOP,
    PID_FILE_ERROR,
    LOG_FILE_ERROR,
    PORT_IN_USE_ERROR,
    BUSY_ERROR,
    START_PROCESS_ERROR,
    NOT_READY_ERROR,
    BASH_SCRIPT_GEN_ERROR,
    BASH_SCRIPT_EXEC_ERROR,
    TIMEOUT_ERROR,
    OPERATION_NOT_PERMITTED_ERROR,
    CANCELLED,
    ABORT,
    TIMEOUT,
    PROCESS_KILLED,
    NOT_READY,
    UNKNOWN,
    ALREADY_STARTING,
    ALREADY_STOPPING,
    DIRECTORY_DOES_NOT_EXIST,
    DIRECTORY_ALREADY_EXISTS,
    FILE_DOES_NOT_EXIST,
    FILE_ALREADY_EXIST,
    FS_ERROR,
    POCO_ERROR,
    IPFS_ERROR,
    REDIS_ERROR,
    SMS_ERROR,
    GANACHE_ERROR,
    MONGO_ERROR,
    CORE_ERROR,
    WORKER_ERROR,
    MARKET_ERROR,
    MARKET_API_ERROR,
    MARKET_WATCHER_ERROR,
    PKGMGR_ERROR,
    DBDIR_ERROR,
    GRADLEW_ERROR,
    GIT_ERROR,
    YML_PARSE_ERROR,
    SIGNATURE_CONFLICT_ERROR,
    NOT_STRICT_POSITVE_INT,
    NULLISH_OR_EMPTY_STRING,
    DOCKER_ERROR
};
